dist: trusty
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=style

before_install:
 - sudo add-apt-repository ppa:0k53d-karl-f830m/openssl
 - sudo apt-get update && sudo apt-get upgrade openssl
install: pip install tox coveralls

script: tox

cache:
  directories:
  - $HOME/.cache/pip

after_success:
  - coveralls
